# Generated by Django 3.2.16 on 2022-12-07 02:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Testing - Shop', 'verbose_name_plural': 'Testing - Shop'},
        ),
        migrations.RemoveField(
            model_name='shop',
            name='location',
        ),
        migrations.AddField(
            model_name='shop',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='Open',
            field=models.BooleanField(verbose_name='Is the shop is open?'),
        ),
    ]
