# Generated by Django 3.2.16 on 2022-12-07 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20221207_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='name_shop',
        ),
    ]
