# Generated by Django 3.2.16 on 2022-12-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alamat_anggotakeluarga_isced_attainment_iucn_kbji_keluarga_kodepos_negara_orang_profesi_sitc_spesies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orang',
            name='profesi',
            field=models.ManyToManyField(blank=True, null=True, to='data.Profesi'),
        ),
        migrations.AlterField(
            model_name='orang',
            name='status_kawin',
            field=models.CharField(blank=True, choices=[('Belum Kawin', 'Belum Kawin'), ('Kawin', 'Kawin'), ('Cerai Hidup', 'Cerai Hidup'), ('Cerai Mati', 'Cerai Mati')], max_length=11, null=True),
        ),
    ]
