# Generated by Django 3.2.16 on 2022-12-08 05:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20221208_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iucn',
            name='lokasi_geografis',
        ),
        migrations.AddField(
            model_name='iucn',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
