# Generated by Django 4.1.4 on 2022-12-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_shop_slug_alter_testing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default='NQx2WktsC8Zsv7DRrRVh09XZCKqzFNTZmeWOqPI7', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='testing',
            name='slug',
            field=models.SlugField(default='dF9NgpJZZp5w1yJLavB0tgjYlTtQ5LEIVHrVMoO7', max_length=40, unique=True),
        ),
    ]
