# Generated by Django 4.1.4 on 2022-12-14 13:35

import data.dataset.testing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_shop_slug_alter_testing_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testing',
            options={'verbose_name': 'Testing - Artikel', 'verbose_name_plural': 'Testing - Artikel'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default=data.dataset.testing.get_random_for_slug, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='testing',
            name='slug',
            field=models.SlugField(default=data.dataset.testing.get_random_for_slug, max_length=40, unique=True),
        ),
    ]
