# Generated by Django 4.1.4 on 2022-12-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_testing_options_alter_shop_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Testing - Toko', 'verbose_name_plural': 'Testing - Toko'},
        ),
    ]
