# Generated by Django 4.1.4 on 2022-12-19 11:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_shop_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iucn',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Sebaran Geografis'),
        ),
    ]
