# Generated by Django 4.1.4 on 2022-12-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_iucn_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spesies',
            name='phylum',
            field=models.CharField(max_length=50, verbose_name='Phylum/Division'),
        ),
    ]
