# Generated by Django 4.1.4 on 2022-12-22 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0013_alter_spesies_phylum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='testing',
            name='slug',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=30)),
                ('foto', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.FileField(upload_to='testing/'), size=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deskripsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.testing')),
                ('toko', models.ManyToManyField(blank=True, null=True, to='data.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testing - Produk',
                'verbose_name_plural': 'Testing - Produk',
            },
        ),
    ]
