# Generated by Django 4.1.4 on 2022-12-22 07:14

import data.dataset.testing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_product_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='testing/', validators=[data.dataset.testing.file_image]),
        ),
    ]
