# Generated by Django 4.1.4 on 2023-01-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_alter_orang_profesi_alter_product_deskripsi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alamat',
            options={'permissions': [('search_alamat', 'Can Search Alamat in Dictionary')], 'verbose_name': 'Alamat', 'verbose_name_plural': 'Alamat'},
        ),
    ]
