# Generated by Django 4.1.4 on 2023-01-12 06:29

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0019_alter_alamat_options_alter_kbji_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orang',
            name='alamat',
            field=models.ForeignKey(help_text='Gunakan tabel <a target="blank" href="/dict/alamat/">Alamat</a> sebagai referensi untuk mengisi bagian ini', on_delete=django.db.models.deletion.CASCADE, to='data.alamat'),
        ),
        migrations.CreateModel(
            name='Lahan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Lahan')),
                ('status_petani', models.CharField(choices=[('pemilik', 'Pemilik Lahan'), ('penggarap', 'Penggarap Lahan')], max_length=10)),
                ('jenis_legalitas', models.CharField(blank=True, choices=[('shm', 'Hak Milik'), ('sewa', 'Hak Sewa'), ('guna_lahan', 'Hak Guna Lahan'), ('guna_bangunan', 'Hak Guna Bangunan'), ('girik', 'Girik'), ('skt', 'Surat Keterangan Tanah'), ('adat', 'Tanah Adat'), ('tanpa_status', 'Tidak ada Status (Komunal)')], max_length=15, null=True)),
                ('nomor_legalitas', models.CharField(max_length=20)),
                ('tahun_legalitas', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1900)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('petani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.orang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lahan',
                'verbose_name_plural': 'Lahan',
            },
        ),
    ]
