# Generated by Django 4.1.4 on 2023-01-12 07:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_alter_orang_alamat_lahan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lahan',
            options={'permissions': [('search_lahan', 'Can search Lahan in Dictionary')], 'verbose_name': 'Lahan', 'verbose_name_plural': 'Lahan'},
        ),
        migrations.AlterField(
            model_name='lahan',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Lahan'),
        ),
    ]
