# Generated by Django 4.1.4 on 2023-01-17 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0022_alter_lahan_jenis_legalitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Kegiatan')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai Kegiatan')),
                ('tanggal_selesai', models.DateField(verbose_name='Tanggal Selesai Kegiatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kegiatan',
                'verbose_name_plural': 'Kegiatan',
                'permissions': [('search_kegiatan', 'Can search Kegiatan in Dictionary')],
            },
        ),
        migrations.AlterField(
            model_name='lahan',
            name='petani',
            field=models.ForeignKey(help_text='Gunakan tabel <a target="blank" href="/dict/orang/">Orang</a> sebagai referensi untuk mengisi bagian ini', on_delete=django.db.models.deletion.CASCADE, to='data.orang'),
        ),
        migrations.CreateModel(
            name='PesertaKegiatan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_kehadiran', models.CharField(choices=[('Peserta', 'Peserta'), ('Narasumber', 'Narasumber'), ('Panitia', 'Panitia')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.kegiatan')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.orang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Peserta Kegiatan',
                'verbose_name_plural': 'Peserta Kegiatan',
            },
        ),
        migrations.CreateModel(
            name='FotoKegiatan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.kegiatan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto Kegiatan',
                'verbose_name_plural': 'Foto Kegiatan',
            },
        ),
    ]
