# Generated by Django 4.1.4 on 2023-01-22 13:37

import data.dataset.kegiatan
import data.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_kegiatan_alter_lahan_petani_pesertakegiatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotokegiatan',
            name='foto',
            field=models.ImageField(upload_to=data.dataset.kegiatan.FotoKegiatan.get_filename),
        ),
        migrations.AlterField(
            model_name='pesertakegiatan',
            name='kegiatan',
            field=models.ForeignKey(help_text='Gunakan tabel <a target="blank" href="/dict/kegiatan/">Kegiatan</a> sebagai referensi untuk mengisi bagian ini', on_delete=django.db.models.deletion.CASCADE, to='data.kegiatan'),
        ),
        migrations.AlterField(
            model_name='pesertakegiatan',
            name='peserta',
            field=models.ForeignKey(help_text='Gunakan tabel <a target="blank" href="/dict/orang/">Orang</a> sebagai referensi untuk mengisi bagian ini', on_delete=django.db.models.deletion.CASCADE, to='data.orang'),
        ),
        migrations.AlterField(
            model_name='product',
            name='foto',
            field=models.FileField(blank=True, help_text='Gunakan file ekstensi .jpg, .jpeg atau .png', null=True, upload_to='dataset/testing/produk', validators=[data.validators.file_image]),
        ),
    ]
