# Generated by Django 4.1.4 on 2023-01-25 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_alter_fotokegiatan_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotokegiatan',
            name='kegiatan',
            field=models.ForeignKey(help_text='Gunakan tabel <a target="blank" href="/dict/kegiatan/">Kegiatan</a> sebagai referensi untuk mengisi bagian ini', on_delete=django.db.models.deletion.CASCADE, to='data.kegiatan'),
        ),
    ]
