# Generated by Django 4.1.4 on 2023-02-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_orang_keterangan_orang_status_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='zoom',
            field=models.IntegerField(default=15),
        ),
    ]
