# Generated by Django 4.1.4 on 2023-02-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_shop_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status_data',
            field=models.CharField(choices=[('Updated', 'Updated'), ('Need Confirmation', 'Need Confirmation'), ('Not Valid', 'Not Valid')], default='Need Confirmation', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='status_data',
            field=models.CharField(choices=[('Updated', 'Updated'), ('Need Confirmation', 'Need Confirmation'), ('Not Valid', 'Not Valid')], default='Need Confirmation', max_length=20),
        ),
        migrations.AddField(
            model_name='testing',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testing',
            name='status_data',
            field=models.CharField(choices=[('Updated', 'Updated'), ('Need Confirmation', 'Need Confirmation'), ('Not Valid', 'Not Valid')], default='Need Confirmation', max_length=20),
        ),
    ]
