# Generated by Django 4.1.4 on 2023-02-09 03:23

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0029_lahanlegalitas_remove_lahan_jenis_legalitas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lahan',
            name='geom',
        ),
        migrations.AlterField(
            model_name='lahan',
            name='legalitas',
            field=models.OneToOneField(blank=True, help_text='Gunakan tabel <a target="blank" href="/dict/lahan/legalitas/">Legalitas Lahan</a> sebagai referensi untuk mengisi bagian ini', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.lahanlegalitas'),
        ),
        migrations.CreateModel(
            name='LahanPoligon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Lahan')),
                ('status_data', models.CharField(choices=[('Updated', 'Updated'), ('Need Confirmation', 'Need Confirmation'), ('Not Valid', 'Not Valid')], default='Need Confirmation', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poligon Lahan',
                'verbose_name_plural': 'Poligon Lahan',
                'permissions': [('search_lahanpoligon', 'Can search Poligon Lahan in Dictionary')],
            },
        ),
        migrations.AddField(
            model_name='lahan',
            name='poligon_lahan',
            field=models.OneToOneField(blank=True, help_text='Gunakan tabel <a target="blank" href="/dict/lahan/poligon">Poligon Lahan</a> sebagai referensi untuk mengisi bagian ini', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.lahanpoligon'),
        ),
    ]
