# Generated by Django 4.1.4 on 2023-02-13 03:59

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0030_remove_lahan_geom_alter_lahan_legalitas_lahanpoligon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iucn',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, db_index=True, null=True, srid=4326, verbose_name='Sebaran Geografis'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, null=True, srid=4326, verbose_name='Location'),
        ),
        migrations.CreateModel(
            name='Demografi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tahun', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1900)])),
                ('penduduk_lakilaki', models.PositiveIntegerField()),
                ('penduduk_perempuan', models.PositiveIntegerField()),
                ('dasar_hukum', models.CharField(max_length=120)),
                ('status_data', models.CharField(choices=[('Updated', 'Updated'), ('Depreciated', 'Depreciated')], max_length=11, verbose_name='Status Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alamat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.alamat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demografi',
                'verbose_name_plural': 'Demografi',
                'permissions': [('search_demografi', 'Can search Demografi in Dictionary')],
            },
        ),
    ]
