# Generated by Django 4.1.4 on 2023-02-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_alter_iucn_geom_alter_lahanpoligon_geom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lahan',
            name='status_petani',
            field=models.CharField(blank=True, choices=[('pemilik', 'Pemilik Lahan'), ('penggarap', 'Penggarap Lahan')], max_length=10, null=True),
        ),
    ]
