# Generated by Django 4.1.4 on 2023-02-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_alter_lahanlegalitas_nomor_legalitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lahanlegalitaslingkungan',
            name='nomor_dokumen',
            field=models.CharField(max_length=40),
        ),
    ]
