# Generated by Django 4.1.4 on 2023-02-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_alter_lahanlegalitaslingkungan_nomor_dokumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lahanlegalitasstdb',
            name='nomor_dokumen',
            field=models.CharField(max_length=40),
        ),
    ]
