# Generated by Django 4.1.4 on 2023-02-15 08:12

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.hstore
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0036_alter_lahanlegalitasstdb_nomor_dokumen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konsesi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Lahan')),
                ('jenis_konsesi', models.CharField(max_length=40)),
                ('catatan_komoditas', models.TextField(blank=True, null=True)),
                ('nomor_legal_konsesi', models.CharField(max_length=40)),
                ('pemegang_konsesi', models.CharField(max_length=100)),
                ('group_perusahaan', models.CharField(blank=True, max_length=100, null=True)),
                ('tahun_konsesi', models.PositiveSmallIntegerField(default=1900, validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1900)])),
                ('sertifikasi', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Diisi sesuai dengan sertifikasi yang berkaitan e.g. RSPO. Lihat dictionary terkait penamaan Key', null=True)),
                ('status_data', models.CharField(choices=[('Updated', 'Updated'), ('Need Confirmation', 'Need Confirmation'), ('Not Valid', 'Not Valid')], default='Need Confirmation', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('komoditas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.sitc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konsesi',
                'verbose_name_plural': 'Konsesi',
                'permissions': [('search_lahanpoligon', 'Can search Konsesi in Dictionary')],
            },
        ),
    ]
