# Generated by Django 4.1.4 on 2023-02-15 12:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_konsesi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konsesi',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Lahan'),
        ),
    ]
