# Generated by Django 4.1.4 on 2023-02-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_alter_konsesi_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='konsesi',
            name='source_id',
            field=models.CharField(default='test', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
