# Generated by Django 4.1.4 on 2023-02-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_konsesi_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konsesi',
            name='nomor_legal_konsesi',
            field=models.CharField(max_length=80),
        ),
    ]
