# Generated by Django 4.1.4 on 2023-02-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_alter_konsesi_nomor_legal_konsesi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lahanlegalitaslingkungan',
            name='nomor_dokumen',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='lahanlegalitasstdb',
            name='nomor_dokumen',
            field=models.CharField(max_length=60),
        ),
    ]
