# Generated by Django 4.1.4 on 2023-03-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_alter_lahanlegalitaslingkungan_nomor_dokumen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilayahdesa',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
