# Generated by Django 4.1.4 on 2023-03-03 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_wilayahdesa_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wilayahdesa',
            name='alamat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.alamat'),
        ),
    ]
