# Generated by Django 4.1.4 on 2023-03-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_alter_wilayahdesa_alamat'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='status_data',
            field=models.CharField(choices=[('Updated', 'Updated'), ('Need Confirmation', 'Need Confirmation'), ('Not Valid', 'Not Valid')], default='Need Confirmation', max_length=20),
        ),
    ]
