# Generated by Django 4.1.4 on 2023-03-07 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0044_kegiatan_keterangan_kegiatan_status_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosisiOrganisasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_posisi', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Posisi Organisasi',
                'verbose_name_plural': 'Posisi Organisasi',
            },
        ),
        migrations.CreateModel(
            name='Organisasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_data', models.CharField(choices=[('Updated', 'Updated'), ('Need Confirmation', 'Need Confirmation'), ('Not Valid', 'Not Valid')], max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alamat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.alamat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organisasi',
                'verbose_name_plural': 'Organisasi',
                'permissions': [('search_organisasi', 'Can search Organisasi in Dictionary')],
            },
        ),
        migrations.CreateModel(
            name='NamaOrganisasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_organisasi', models.CharField(max_length=80)),
                ('status_organisasi', models.CharField(choices=[('Badan Hukum', 'Badan Hukum'), ('Non Badan Hukum', 'Non Badan Hukum'), ('Tidak diketahui', 'Tidak diketahui')], max_length=20)),
                ('nama_notaris', models.CharField(blank=True, max_length=50, null=True)),
                ('nomor_notaris', models.CharField(blank=True, max_length=30, null=True)),
                ('tanggal_notaris', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.organisasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nama Organisasi',
                'verbose_name_plural': 'Nama Organisasi',
            },
        ),
        migrations.CreateModel(
            name='KeanggotaanOrganisasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bergabung_sejak', models.DateField(default='1900-01-01')),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Non Aktif', 'Non Aktif')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.orang')),
                ('organisasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.organisasi')),
                ('posisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.posisiorganisasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Keanggotaan Organisasi',
                'verbose_name_plural': 'Keanggotaan Organisasi',
            },
        ),
    ]
