# Generated by Django 4.1.4 on 2023-03-07 07:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0045_posisiorganisasi_organisasi_namaorganisasi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LahanLegalitasSertifikasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomor_dokumen', models.CharField(max_length=60)),
                ('tahun_dokumen', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1900)])),
                ('status_dokumen', models.CharField(choices=[('Berlaku', 'Berlaku'), ('Tidak Berlaku', 'Tidak Berlaku')], max_length=20)),
                ('status_data', models.CharField(choices=[('Updated', 'Updated'), ('Need Confirmation', 'Need Confirmation'), ('Not Valid', 'Not Valid')], default='Need Confirmation', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legalitas_lahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.lahanlegalitas')),
                ('organisasi_pendaftar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.organisasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legalitas Lahan - Dokumen Sertifikasi ',
                'verbose_name_plural': 'Legalitas Lahan - Dokumen Sertifikasi',
                'permissions': [('search_lahanlegalitassertifikasi', 'Can search Legalitas Lahan - Dokumen Sertifikasi in Dictionary')],
            },
        ),
    ]
