# Generated by Django 4.1.4 on 2023-03-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_organisasi_kode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisasi',
            name='kode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
