# Generated by Django 4.1.4 on 2023-03-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_alter_organisasi_kode'),
    ]

    operations = [
        migrations.AddField(
            model_name='namaorganisasi',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
