# Generated by Django 4.1.4 on 2023-03-14 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_namaorganisasi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='alamat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.alamat'),
        ),
    ]
