# Generated by Django 4.1.4 on 2023-03-14 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_kegiatan_alamat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='alamat',
            field=models.ForeignKey(blank=True, help_text='Gunakan tabel <a target="blank" href="/dict/alamat/">Alamat</a> sebagai referensi untuk mengisi bagian ini', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.alamat'),
        ),
    ]
