# Generated by Django 4.1.4 on 2023-03-24 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_alter_kegiatan_alamat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wilayahdesa',
            old_name='keterangan',
            new_name='metadata',
        ),
        migrations.RemoveField(
            model_name='wilayahdesa',
            name='dasar_hukum',
        ),
        migrations.AddField(
            model_name='wilayahdesa',
            name='alamat_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alamat_2', to='data.alamat'),
        ),
        migrations.AddField(
            model_name='wilayahdesa',
            name='alamat_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alamat_3', to='data.alamat'),
        ),
        migrations.AddField(
            model_name='wilayahdesa',
            name='alamat_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alamat_4', to='data.alamat'),
        ),
        migrations.AddField(
            model_name='wilayahdesa',
            name='catatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wilayahdesa',
            name='source_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wilayahdesa',
            name='srs',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wilayahdesa',
            name='alamat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alamat', to='data.alamat'),
        ),
    ]
