# Generated by Django 4.1.4 on 2023-03-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_rename_keterangan_wilayahdesa_metadata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wilayahdesa',
            old_name='alamat',
            new_name='alamat_1',
        ),
    ]
