# Generated by Django 4.1.4 on 2023-04-14 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0053_rename_alamat_wilayahdesa_alamat_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='KonflikTerlapor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Individu', 'Individu'), ('Kelompok', 'Kelompok')], max_length=20)),
                ('status_data', models.CharField(choices=[('Updated', 'Updated'), ('Need Confirmation', 'Need Confirmation'), ('Not Valid', 'Not Valid')], default='Need Confirmation', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alamat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.alamat')),
                ('terlapor_individu', models.ForeignKey(blank=True, help_text='Diisi jika statusnya <b>Individu</b>', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.orang')),
                ('terlapor_kelompok', models.ForeignKey(blank=True, help_text='Diisi jika statusnya <b>Kelompok</b>', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.organisasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konflik - Terlapor',
                'verbose_name_plural': 'Konflik - Terlapor',
            },
        ),
        migrations.CreateModel(
            name='KonflikPelapor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Individu', 'Individu'), ('Kelompok', 'Kelompok')], max_length=20)),
                ('keluarga_terdampak', models.PositiveSmallIntegerField()),
                ('status_data', models.CharField(choices=[('Updated', 'Updated'), ('Need Confirmation', 'Need Confirmation'), ('Not Valid', 'Not Valid')], default='Need Confirmation', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alamat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.alamat')),
                ('pelapor_individu', models.ForeignKey(blank=True, help_text='Diisi jika statusnya <b>Individu</b>', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.orang')),
                ('pelapor_kelompok', models.ForeignKey(blank=True, help_text='Diisi jika statusnya <b>Kelompok</b>', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.organisasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konflik - Pelapor',
                'verbose_name_plural': 'Konflik - Pelapor',
            },
        ),
        migrations.CreateModel(
            name='KonflikDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_lahan', models.CharField(max_length=20)),
                ('alasan_hak', models.CharField(max_length=20)),
                ('alasan_konflik', models.TextField()),
                ('luas_konflik', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tuntutan', models.TextField()),
                ('pernah_diselesaikan', models.BooleanField()),
                ('waktu_penyelesaian', models.DateField()),
                ('mediator', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('upaya_penyelesaian', models.TextField()),
                ('penyelesaian_akhir', models.TextField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('status_data', models.CharField(choices=[('Updated', 'Updated'), ('Need Confirmation', 'Need Confirmation'), ('Not Valid', 'Not Valid')], default='Need Confirmation', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konflik - Detail',
                'verbose_name_plural': 'Konflik - Detail',
            },
        ),
        migrations.CreateModel(
            name='Konflik',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no_registrasi', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(max_length=15)),
                ('tahun', models.SmallIntegerField()),
                ('tipologi', models.CharField(max_length=70)),
                ('status_data', models.CharField(choices=[('Updated', 'Updated'), ('Need Confirmation', 'Need Confirmation'), ('Not Valid', 'Not Valid')], default='Need Confirmation', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.orang')),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.alamat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konflik',
                'verbose_name_plural': 'Konflik',
                'permissions': [('search_konflik', 'Can search Konflik in Dictionary')],
            },
        ),
    ]
