# Generated by Django 4.1.4 on 2023-04-14 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0054_konflikterlapor_konflikpelapor_konflikdetail_konflik'),
    ]

    operations = [
        migrations.AddField(
            model_name='konflikdetail',
            name='konflik',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.konflik'),
        ),
        migrations.AddField(
            model_name='konflikpelapor',
            name='konflik',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.konflik'),
        ),
        migrations.AddField(
            model_name='konflikterlapor',
            name='konflik',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.konflik'),
        ),
    ]
