# Generated by Django 4.1.4 on 2023-07-21 08:41

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0056_alter_konflikdetail_konflik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetaniSTDB',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nik', models.CharField(blank=True, max_length=16, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('nkk', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('no_telepon', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid number', message='Input must a valid number', regex='\\d+')])),
                ('keanggotaan_organisasi', models.CharField(blank=True, max_length=25, null=True)),
                ('keanggotaan_organisasi_id', models.CharField(blank=True, max_length=25, null=True)),
                ('keanggotaan_organisasi_lainnya', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_organisasi', models.CharField(blank=True, max_length=100, null=True)),
                ('sumber_data', models.CharField(blank=True, max_length=20, null=True)),
                ('sumber_data_id', models.CharField(blank=True, max_length=20, null=True)),
                ('sumber_data_lainnya', models.CharField(blank=True, max_length=100, null=True)),
                ('kode_provinsi', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)])),
                ('kode_kabupaten', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)])),
                ('kode_kecamatan', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)])),
                ('kode_desa', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('no_rt', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(100)])),
                ('no_rw', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(100)])),
                ('alamat_lengkap', models.TextField(blank=True, null=True)),
                ('validasi_data', models.BooleanField(default=False)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('user_last_edit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LahanSTDB',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_kepemilikan_lahan', models.CharField(blank=True, max_length=30, null=True)),
                ('status_kepemilikan_lahan_id', models.CharField(blank=True, max_length=30, null=True)),
                ('status_kepemilikan_lahan_lainnya', models.CharField(blank=True, max_length=50, null=True)),
                ('nomor_registrasi_kepemilikan', models.CharField(blank=True, max_length=100, null=True)),
                ('luas_polygon_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('luas_bukti_kepemilikan_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('komoditas', models.CharField(blank=True, max_length=50, null=True)),
                ('komoditas_id', models.CharField(blank=True, max_length=50, null=True)),
                ('produksi_tahunan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tempat_jual', models.CharField(blank=True, max_length=30, null=True)),
                ('tempat_jual_id', models.CharField(blank=True, max_length=30, null=True)),
                ('nama_pembeli', models.CharField(blank=True, max_length=50, null=True)),
                ('tahun_tanam', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('jumlah_pohon', models.PositiveIntegerField(blank=True, null=True)),
                ('pola_tanam', models.CharField(blank=True, max_length=30, null=True)),
                ('pola_tanam_id', models.CharField(blank=True, max_length=30, null=True)),
                ('jenis_lahan', models.CharField(blank=True, max_length=30, null=True)),
                ('jenis_lahan_id', models.CharField(blank=True, max_length=30, null=True)),
                ('asal_benih', models.CharField(blank=True, max_length=50, null=True)),
                ('asal_benih_id', models.CharField(blank=True, max_length=50, null=True)),
                ('asal_benih_lainnya', models.CharField(blank=True, max_length=50, null=True)),
                ('jenis_pupuk', models.CharField(blank=True, max_length=50, null=True)),
                ('jenis_pupuk_id', models.CharField(blank=True, max_length=50, null=True)),
                ('mitra_pengolahan', models.CharField(blank=True, max_length=50, null=True)),
                ('mitra_pengolahan_id', models.CharField(blank=True, max_length=50, null=True)),
                ('mitra_pengolahan_lainnya', models.CharField(blank=True, max_length=50, null=True)),
                ('usaha_lain_kebun', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, db_index=True, null=True, srid=4326)),
                ('kode_provinsi', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)])),
                ('kode_kabupaten', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)])),
                ('kode_kecamatan', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)])),
                ('kode_desa', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('no_rt', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(100)])),
                ('no_rw', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(100)])),
                ('alamat_lengkap', models.TextField(blank=True, null=True)),
                ('validasi_data', models.BooleanField(default=False)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('petani_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.petanistdb')),
                ('user_last_edit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
