# Generated by Django 4.1.4 on 2023-07-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_petanistdb_lahanstdb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lahanstdb',
            options={'permissions': [('search_lahan_stdb', 'Can search Lahan STDB in Dictionary')], 'verbose_name': '[TEMPORARY] Lahan STDB', 'verbose_name_plural': '[TEMPORARY] Lahan STDB'},
        ),
        migrations.AlterModelOptions(
            name='petanistdb',
            options={'permissions': [('search_petani_stdb', 'Can search petani STDB in Dictionary')], 'verbose_name': '[TEMPORARY] Petani STDB', 'verbose_name_plural': '[TEMPORARY] Petani STDB'},
        ),
    ]
