# Generated by Django 4.1.4 on 2023-07-21 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_alter_lahanstdb_options_alter_petanistdb_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lahanstdb',
            name='kode_desa',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='lahanstdb',
            name='kode_provinsi',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='petanistdb',
            name='kode_desa',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='petanistdb',
            name='kode_provinsi',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)]),
        ),
    ]
