# Generated by Django 4.1.4 on 2022-12-14 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=40, verbose_name='Nama Form')),
                ('url_path', models.CharField(max_length=80, verbose_name='URL Path')),
                ('url_alias', models.CharField(max_length=80, verbose_name='URL Alias')),
            ],
        ),
    ]
