# Generated by Django 4.1.4 on 2022-12-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forms',
            options={'verbose_name': 'Form', 'verbose_name_plural': 'Forms'},
        ),
        migrations.RemoveField(
            model_name='forms',
            name='url_alias',
        ),
        migrations.AddField(
            model_name='forms',
            name='perms',
            field=models.CharField(default='can_view_Testing_Data', max_length=80, verbose_name='Nama Permission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forms',
            name='url_add',
            field=models.CharField(default='can_view_Testing_Data', max_length=80, verbose_name='URL Tambah Data'),
            preserve_default=False,
        ),
    ]
