# Generated by Django 4.1.4 on 2022-12-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_alter_forms_options_remove_forms_url_alias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='perms',
        ),
        migrations.AddField(
            model_name='forms',
            name='perms_add',
            field=models.CharField(default='test', max_length=80, verbose_name='Add Permission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forms',
            name='perms_view',
            field=models.CharField(default='test', max_length=80, verbose_name='View Permission'),
            preserve_default=False,
        ),
    ]
