# Generated by Django 4.1.4 on 2022-12-20 01:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_remove_forms_perms_forms_perms_add_forms_perms_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=40)),
                ('gambar', models.FileField(upload_to='')),
                ('deskripsi', models.TextField()),
                ('deskripsi_data', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
            options={
                'verbose_name': 'Documentation',
                'verbose_name_plural': 'Documentations',
            },
        ),
    ]
