# Generated by Django 4.1.4 on 2022-12-20 07:53

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='docs',
            name='deskripsi_data',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
        migrations.AlterField(
            model_name='docs',
            name='gambar',
            field=models.FileField(upload_to='docs/'),
        ),
    ]
