# Generated by Django 4.1.4 on 2022-12-21 02:12

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_docs_updated_at_alter_docs_deskripsi_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='kolom_data',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=30), default='{test, test, test}', size=None),
            preserve_default=False,
        ),
    ]
