# Generated by Django 4.1.4 on 2022-12-21 02:36

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_docs_kolom_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='dict_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
