# Generated by Django 4.1.4 on 2022-12-21 03:26

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_docs_dict_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='deskripsi_data',
        ),
        migrations.RemoveField(
            model_name='docs',
            name='dict_data',
        ),
        migrations.RemoveField(
            model_name='docs',
            name='kolom_data',
        ),
        migrations.AddField(
            model_name='docs',
            name='dictionary_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name='Dictionary'),
        ),
    ]
