# Generated by Django 4.1.4 on 2022-12-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_remove_docs_deskripsi_data_remove_docs_dict_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('url_path', models.CharField(max_length=80, verbose_name='URL Path')),
            ],
            options={
                'verbose_name_plural': 'Dictionaries',
            },
        ),
    ]
