# Generated by Django 4.1.4 on 2022-12-23 06:46

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_dictionary_perms_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('Live', 'Live'), ('Analytics', 'Analytics')], max_length=10)),
                ('email_maintainer', models.CharField(max_length=40)),
                ('embed_url', models.CharField(max_length=80, verbose_name='URL Path')),
                ('width', models.CharField(help_text="Gunakan CSS unit seperti 'cm', 'mm', 'in', 'px', 'pt', dan 'pc'. Contoh: 500px", max_length=8)),
                ('height', models.CharField(help_text="Gunakan CSS unit seperti 'cm', 'mm', 'in', 'px', 'pt', dan 'pc'. Contoh: 500px", max_length=8)),
                ('perms_view', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None)),
            ],
        ),
    ]
