# Generated by Django 4.1.4 on 2022-12-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='embed_url',
            field=models.CharField(max_length=100, verbose_name='URL Path'),
        ),
    ]
