# Generated by Django 4.1.4 on 2022-12-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_alter_dashboard_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='page_url',
            field=models.CharField(default='test', max_length=80, verbose_name='Page URL Path'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='embed_url',
            field=models.CharField(max_length=100, verbose_name='Embed URL Path'),
        ),
    ]
