# Generated by Django 4.1.4 on 2022-12-24 02:34

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_dashboard_page_url_alter_dashboard_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='category',
            field=models.CharField(choices=[('Live (database)', 'Live (database)'), ('Live (spreadsheet)', 'Live (spreadsheet)'), ('Static', 'Static'), ('Analytics', 'Analytics')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='height',
            field=models.CharField(help_text="Gunakan CSS unit seperti '%', 'cm', 'mm', 'in', 'px', 'pt', dan 'pc'. Contoh: 500px", max_length=8),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='perms_view',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='width',
            field=models.CharField(help_text="Gunakan CSS unit seperti '%', 'cm', 'mm', 'in', 'px', 'pt', dan 'pc'. Contoh: 500px", max_length=8),
        ),
    ]
