# Generated by Django 4.1.4 on 2022-12-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0015_catalog_alter_dashboard_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='embed_url',
            field=models.CharField(max_length=150, verbose_name='Embed URL Path'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='spreadsheet_url',
            field=models.CharField(max_length=150, verbose_name='Embed URL Path'),
        ),
    ]
