# Generated by Django 4.1.4 on 2022-12-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0016_alter_catalog_embed_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='embed_url',
            field=models.URLField(verbose_name='Embed URL Path'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='spreadsheet_url',
            field=models.URLField(verbose_name='Google Sheets URL Path'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='embed_url',
            field=models.URLField(max_length=100, verbose_name='Embed URL Path'),
        ),
    ]
