# Generated by Django 4.1.4 on 2023-01-10 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0018_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('/static/images/avatar/brownbear.png', 'Brown Bear'), ('/static/images/avatar/bull.png', 'Bull'), ('/static/images/avatar/camel.png', 'Camel'), ('/static/images/avatar/capybara.png', 'Capybara'), ('/static/images/avatar/cat.png', 'Cat'), ('/static/images/avatar/chicken.png', 'Chicken'), ('/static/images/avatar/chimp.png', 'Chimp'), ('/static/images/avatar/cow.png', 'Cow'), ('/static/images/avatar/deer.png', 'Deer'), ('/static/images/avatar/dog.png', 'Dog'), ('/static/images/avatar/donkey.png', 'Donkey'), ('/static/images/avatar/duck.png', 'Duck'), ('/static/images/avatar/eagle.png', 'Eagle'), ('/static/images/avatar/elephant.png', 'Elephant'), ('/static/images/avatar/femaledeer.png', 'Female Deer'), ('/static/images/avatar/flamingo.png', 'Flamingo'), ('/static/images/avatar/fox.png', 'Fox'), ('/static/images/avatar/frog.png', 'Frog'), ('/static/images/avatar/giraffe.png', 'Giraffe'), ('/static/images/avatar/gorilla.png', 'Gorilla'), ('/static/images/avatar/hippo.png', 'Hippo'), ('/static/images/avatar/horse.png', 'Horse'), ('/static/images/avatar/kangaroo.png', 'Kangaroo'), ('/static/images/avatar/koala.png', 'Koala'), ('/static/images/avatar/lemur.png', 'Lemur'), ('/static/images/avatar/lion.png', 'Lion'), ('/static/images/avatar/llama.png', 'Llama'), ('/static/images/avatar/monkey.png', 'Monkey'), ('/static/images/avatar/mouse.png', 'Mouse'), ('/static/images/avatar/nutria.png', 'Nutria'), ('/static/images/avatar/otter.png', 'Otter'), ('/static/images/avatar/owl.png', 'Owl'), ('/static/images/avatar/panda.png', 'Panda'), ('/static/images/avatar/panther.png', 'Panther'), ('/static/images/avatar/penguin.png', 'Penguin'), ('/static/images/avatar/pig.png', 'Pig'), ('/static/images/avatar/prairiedog.png', 'Prairie Dog'), ('/static/images/avatar/rabbit.png', 'Rabbit'), ('/static/images/avatar/racoon.png', 'Racoon'), ('/static/images/avatar/redpanda.png', 'Redpanda'), ('/static/images/avatar/rhino.png', 'Rhino'), ('/static/images/avatar/seal.png', 'Seal'), ('/static/images/avatar/sheep.png', 'Sheep'), ('/static/images/avatar/sloth.png', 'Sloth'), ('/static/images/avatar/snake.png', 'Snake'), ('/static/images/avatar/tiger.png', 'Tiger'), ('/static/images/avatar/toucan.png', 'Toucan'), ('/static/images/avatar/turtle.png', 'Turtle'), ('/static/images/avatar/walrus.png', 'Walrus'), ('/static/images/avatar/whitebear.png', 'White Bear'), ('/static/images/avatar/wombat.png', 'Wombat'), ('/static/images/avatar/zebra.png', 'Zebra')], default='/static/images/avatar/chimp.png', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
