# Generated by Django 4.1.4 on 2023-01-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0020_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
