# Generated by Django 4.1.4 on 2023-01-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0021_remove_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
