# Generated by Django 4.1.4 on 2023-01-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0022_webentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webentry',
            options={'verbose_name_plural': 'Web Entries'},
        ),
        migrations.AddField(
            model_name='webentry',
            name='browser_type',
            field=models.CharField(default='None', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webentry',
            name='browser_version',
            field=models.CharField(default='None', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webentry',
            name='device_brand',
            field=models.CharField(default='None', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webentry',
            name='device_model',
            field=models.CharField(default='None', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webentry',
            name='device_type',
            field=models.CharField(default='None', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webentry',
            name='electronic',
            field=models.CharField(default='None', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webentry',
            name='is_bot',
            field=models.BooleanField(default=False, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webentry',
            name='is_touchscreen',
            field=models.BooleanField(default=False, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webentry',
            name='os_type',
            field=models.CharField(default='None', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webentry',
            name='os_version',
            field=models.CharField(default='None', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webentry',
            name='action',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='webentry',
            name='ip',
            field=models.GenericIPAddressField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='webentry',
            name='username',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
