# Generated by Django 4.1.4 on 2023-01-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0024_alter_docs_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(editable=False, max_length=10)),
                ('dataset', models.CharField(editable=False, max_length=100)),
                ('id_dataset', models.CharField(editable=False, max_length=50)),
                ('user', models.CharField(editable=False, max_length=50)),
                ('ip_user', models.CharField(editable=False, max_length=50)),
                ('device_user', models.CharField(editable=False, max_length=100)),
                ('os_user', models.CharField(editable=False, max_length=100)),
                ('browser_user', models.CharField(editable=False, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
