# Generated by Django 4.1.4 on 2023-01-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0025_datalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_access', models.URLField(editable=False)),
                ('ip', models.GenericIPAddressField(editable=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('electronic', models.CharField(editable=False, max_length=50)),
                ('is_touchscreen', models.BooleanField(editable=False)),
                ('is_bot', models.BooleanField(editable=False)),
                ('os_type', models.CharField(editable=False, max_length=50)),
                ('os_version', models.CharField(editable=False, max_length=50)),
                ('browser_type', models.CharField(editable=False, max_length=50)),
                ('browser_version', models.CharField(editable=False, max_length=50)),
                ('device_type', models.CharField(editable=False, max_length=50)),
                ('device_brand', models.CharField(editable=False, max_length=50)),
                ('device_model', models.CharField(editable=False, max_length=50)),
                ('username', models.CharField(editable=False, max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='webentry',
            options={'verbose_name_plural': 'Web entries'},
        ),
    ]
