# Generated by Django 4.1.4 on 2023-01-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0027_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Process', 'Process'), ('Complete', 'Complete'), ('Decline', 'Decline')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('Add Catalog', 'Add Catalog'), ('Add Dashboard', 'Add Dashboard'), ('Add Dataset', 'Add Dataset'), ('Add Dictionary', 'Add Dictionary'), ('Add Form', 'Add Form'), ('Add Dictionary', 'Add Dictionary'), ('Modify Catalog', 'Modify Catalog'), ('Modify Dashboard', 'Modify Dashboard'), ('Modify Dataset', 'Modify Dataset'), ('Modify Dictionary', 'Modify Dictionary'), ('Modify Form', 'Modify Form'), ('Modify Dictionary', 'Modify Dictionary'), ('Bug Report', 'Bug Report')], max_length=50),
        ),
    ]
