# Generated by Django 4.1.4 on 2023-01-31 03:22

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0030_rename_documents_ppresentation_catalog_documents_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='email_maintainers',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None),
        ),
    ]
