# Generated by Django 4.1.4 on 2023-01-31 04:06

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0031_alter_catalog_email_maintainers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='spreadsheets_link',
        ),
        migrations.AddField(
            model_name='catalog',
            name='bigquery_table',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name=models.CharField(max_length=100)),
        ),
    ]
