# Generated by Django 4.1.4 on 2023-01-31 06:52

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('operation', '0032_remove_catalog_spreadsheets_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='email_maintainer',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='perms_view',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='email_maintainers',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='permission_view',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
