# Generated by Django 4.1.4 on 2023-02-01 09:52

import data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0034_remove_catalog_documents_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogdocument',
            name='documents',
            field=models.FileField(upload_to='catalog', validators=[data.validators.file_doc]),
        ),
    ]
