# Generated by Django 4.1.4 on 2023-02-01 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0035_alter_catalogdocument_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Normal User', 'Normal User'), ('Observer', 'Observer')], default='Normal User', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_observed',
            field=models.ManyToManyField(blank=True, related_name='user_observed', to=settings.AUTH_USER_MODEL),
        ),
    ]
