# Generated by Django 4.1.4 on 2023-02-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0036_profile_status_profile_user_observed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='city',
            field=models.CharField(default='None', editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='country',
            field=models.CharField(default='None', editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='country_code',
            field=models.CharField(default='N/A', editable=False, max_length=5),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='isp',
            field=models.CharField(default='None', editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='isp_detail',
            field=models.CharField(default='None', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='lat',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='lon',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='region',
            field=models.CharField(default='None', editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='region_code',
            field=models.CharField(default='N/A', editable=False, max_length=5),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='timezone',
            field=models.CharField(default='None', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='datalog',
            name='city',
            field=models.CharField(default='None', editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='datalog',
            name='country',
            field=models.CharField(default='None', editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='datalog',
            name='country_code',
            field=models.CharField(default='N/A', editable=False, max_length=5),
        ),
        migrations.AddField(
            model_name='datalog',
            name='isp',
            field=models.CharField(default='None', editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='datalog',
            name='isp_detail',
            field=models.CharField(default='None', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='datalog',
            name='lat',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AddField(
            model_name='datalog',
            name='lon',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AddField(
            model_name='datalog',
            name='region',
            field=models.CharField(default='None', editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='datalog',
            name='region_code',
            field=models.CharField(default='N/A', editable=False, max_length=5),
        ),
        migrations.AddField(
            model_name='datalog',
            name='timezone',
            field=models.CharField(default='None', editable=False, max_length=20),
        ),
    ]
