# Generated by Django 4.1.4 on 2023-02-20 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0037_activitylog_city_activitylog_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='isp_detail',
        ),
        migrations.RemoveField(
            model_name='datalog',
            name='isp_detail',
        ),
    ]
