# Generated by Django 4.1.4 on 2023-02-28 02:51

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0040_docs_deskripsi_kolom_docs_nama_kolom'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='kolom_tabel',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='docs',
            name='deskripsi_kolom',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
