# Generated by Django 4.1.4 on 2023-02-28 04:34

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0041_docs_kolom_tabel_alter_docs_deskripsi_kolom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='deskripsi_kolom',
        ),
        migrations.RemoveField(
            model_name='docs',
            name='kolom_tabel',
        ),
        migrations.AlterField(
            model_name='docs',
            name='nama_kolom',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None, verbose_name='Urutan kolom'),
        ),
    ]
