# Generated by Django 4.1.4 on 2023-03-03 09:13

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0042_remove_docs_deskripsi_kolom_remove_docs_kolom_tabel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogdocument',
            name='sheets',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
    ]
