# Generated by Django 4.1.4 on 2023-03-03 09:18

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0043_catalogdocument_sheets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogdocument',
            name='sheets',
        ),
        migrations.AddField(
            model_name='catalog',
            name='sheets',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
    ]
