# Generated by Django 4.1.4 on 2023-03-08 02:50

from django.db import migrations, models
import operation.ops_models.docs


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0045_remove_catalog_sheets_catalog_google_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='er_diagram',
            field=models.FileField(default='test', upload_to=operation.ops_models.docs.Docs.get_filename_erd, verbose_name='Entity-Relation Diagram'),
            preserve_default=False,
        ),
    ]
