# Generated by Django 4.1.4 on 2023-03-13 12:16

import data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0046_docs_er_diagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='thumbnail',
            field=models.ImageField(default='test', upload_to='catalog/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='thumbnail',
            field=models.ImageField(default='test', upload_to='dashboard/img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogdocument',
            name='documents',
            field=models.FileField(upload_to='catalog/docs', validators=[data.validators.file_doc]),
        ),
    ]
