# Generated by Django 4.1.4 on 2023-03-13 12:21

from django.db import migrations, models
import operation.ops_models.catalogs
import operation.ops_models.dashboards


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0047_catalog_thumbnail_dashboard_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='thumbnail',
            field=models.ImageField(upload_to=operation.ops_models.catalogs.Catalog.get_filename),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='thumbnail',
            field=models.ImageField(upload_to=operation.ops_models.dashboards.Dashboard.get_filename),
        ),
    ]
