# Generated by Django 4.1.4 on 2023-05-22 09:39

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0049_surveyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_exists', models.BooleanField()),
                ('platform_options', models.CharField(blank=True, choices=[('Restorasi Mobile Apps', 'Restorasi Mobile Apps'), ('Konflik Web Apps', 'Konflik Web Apps'), ('E-sertifikasi Web Apps', 'E-sertifikasi Web Apps')], max_length=50, null=True)),
                ('form_type', models.CharField(blank=True, choices=[('Google Spreadsheets', 'Google Spreadsheets'), ('Google Forms', 'Google Forms'), ('Custom Forms', 'Custom Forms')], max_length=50, null=True)),
                ('form_variables', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operation.surveyplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('progress', 'Progress'), ('complete', 'Complete')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operation.surveyform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
